### ISSUE TITLE
Glitch in arrow function syntax highlighting when using 'JetBrains Mono' Font

### ISSUE THREAD

**Issue by meetusadadiya** [nurmohammed840/achievement#11]
Hi, Just tried out this theme while ago and it is awesome, but there is one problem with syntax highlighting with arrow functions in JavaScript.

<img width="403" alt="Screenshot 2021-06-19 at 4 19 41 PM" src="https://user-images.githubusercontent.com/23379240/122640155-8162f380-d11b-11eb-9f11-47f31927d2e4.png">

I am using JetBrains Mono with font ligatures settings on.
It displays everything fine when font ligatures are turned off.

**Comment by nurmohammed840** [comment]
Actually the problem is with ligatures, the theme schema of arrow function is `{ "foreground": "#7FFF00", "fontStyle": "italic bold" }`
you can overwrite theme schema of `storage.type.function.arrow`, so it would look like:

```json
// settings.json
{
	"editor.tokenColorCustomizations": {
		"[Just Black]": {
			"textMateRules": [
				{
					"scope": "storage.type.function.arrow",
					"settings": {
						"foreground": "#7FFF00",
						"fontStyle": ""
					}
				},
			]
		}
	}
}
```
