### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by GoHoo** [nurmohammed840/achievement#14]
Awesome theme but could you please make comments green or even brighter white, because right now they are hard to read.

**Comment by nurmohammed840** [comment]
Glad to know you liked it.

There is lot of thing that need to improve, in this theme.
But I feel lazy to update new  schema.

I agree that comments are hard to see, But you can change the color for this theme in `settings.json`,  For example:

```json
"editor.tokenColorCustomizations": {
  "[Just Black]": {
    "textMateRules": [
         { "scope": "comment.block", "settings": { "foreground": "#0c8" } },
    ]
  }
}
```

I do accept contributions!
