### ISSUE TITLE
I did not was able to register a command

### ISSUE THREAD

**Issue by emuvi** [nurmohammed840/achievement#15]
main.js

```
/// <reference path="c:/Users/emuvi/.vscode/extensions/nur.script-0.2.1/@types/api.global.d.ts" />
/// <reference path="c:/Users/emuvi/.vscode/extensions/nur.script-0.2.1/@types/vscode.global.d.ts" />
//  @ts-check
//  API: https://code.visualstudio.com/api/references/vscode-api

function activate(_context) {
   window.showInformationMessage('Hello, World!');

   commands.registerCommand('extension.sayHello2', () => {
      window.showInformationMessage('Hello World!');
   });
}

function deactivate() {}

module.exports = { activate, deactivate }
```

package.json
```
{
  "name": "helloworld2",
  "displayName": "Hello World 2",
  "version": "0.1.0",
  "description": "Hello World 2.",
  "author": {
    "name": "emuvi"
  },
  "contributes": {
    "commands": [
      {
        "command": "extension.sayHello2",
        "title": "Hello World 2"
      }
    ]
  }
}
```

**Comment by nurmohammed840** [comment]
Is `main.js` located under `.vscode/` folder ?

By default, The primary entry point is : `.vscode/main.js`,  And Of-course   you can modify it!

To change any extension configuration: 
1. click `Script` on status bar
2. then click on `Open Config File` option.

This will open the `package.json` file:

```
C:/Users/emuvi/.vscode/extensions/nur.script-0.2.1/package.json
```

**Comment by emuvi** [comment]
I've done some research and I understand that there's a limitation on VSCode that today we can not programmatic add commands to the IDE. So I think I would have to register commands on package.json of the Script extension, even if the command belongs to a specif project. Which is not great. The work around suggested by some was to register a command in the main package and this command then would show only the commands loaded by the specific project opened. 

This is an ideia of feature.

I come from emacs and there I used to register commands specific for the project opened many times.

Would be nice to have this on VSCode also.

Actually, the initial expectation I had with Script was this.

**Comment by emuvi** [comment]
What you mean is closed? Is there a way to register commands per project? Or remains the behavior of register commands to all projects but that will only work if you are in the project that implements?

**Comment by nurmohammed840** [comment]
> Is there a way to register commands per project ?
 
Is is not possible to register commands per project, AFAIK.

Also, A command should have mono implementation. Can you provide more information on what you are trying to achieve ?

**Comment by emuvi** [comment]
The possible implementation would be the extension register a command like: "Call a project command", and on the main.js expected on the project by this extension, would do the implementation of a particular script to the project that uses a function/feature made available by this extensions to register a scripts/commands/functions that will be listed and executed on the "Call a project command".

Is this possible, right?

VSCode should be able to do at least this, I think, way less than emacs.

**Comment by nurmohammed840** [comment]
I am little confused... Are you trying to call a command `Call a project command` that would many implementation or calling external functions (library)  based on workspace ?

You can do it like so:

 ```js
 function activate(ctx) {
   commands.registerCommand('extension.call_project_command', () => {
      let workspace_path = get_workspace_path(ctx);
      let module_path  = Path.join(workspace_path, "project_command.js");
      if (module_path) {
          println(`Executing: ${module_path}`);
          require(module_path);  
      }
   });
}

function deactivate() {}

module.exports = { activate, deactivate }
 ```

**Comment by emuvi** [comment]
Sorry, but I can't treat this now. Maybe in the future I came back here to we make this project commands better.
