### ISSUE TITLE
This is a great idea, but is there a way to disable "Want to create a script for _____?"

### ISSUE THREAD

**Issue by mattalexander-pantheon** [nurmohammed840/achievement#8]
This is a great idea, but is there a way to disable "Want to create a script for _____?"

**Comment by nurmohammed840** [comment]
Thanks for suggestion, I will make this feature (opt-in) in  next update. I also want to remove all  unnecessary API, Next update will came, Maybe in 2 days...

**Comment by nurmohammed840** [comment]
Sorry for the late patch...
In the latest version 0.2.0, set `script.suggestCreateScript: false`
